
export const LEVELS_JS = [
    {
        level: 1,
        backgroundSprite: "level-1-bg",
        backgroundScale: 6,
        levelNote: {
            text: "'In these halls are spawners three, destroy and thy shall reward thee \ncollect the gems of morganite and escape the fight'"
        },
        hasEnemy: true, // if level contains enemies, prevents enemy function in the scene from running if it contains none
        enemySpeed: 200, 
        enemyScale: 3,
        item: "pickaxe",
        map: [
            "                               ===========================",
            "                               =-                       -=",
            "                               =                         =",
            "                               =                         =",
            "                               =      S                * =",
            "                               =================  ==========----------=",
            "                                  =  =  =  =  ==  ==                 -=",
            "                                  -  -  -  -  ==  ==                  =",
            "                                  =  =  =  =  ==  ==               @ -=",
            "                               =----------------  ----       ==========",
            "                              =-                               =",
            "      =   =   =   =          =-                                =",
            "    ==-   -===-   -==       =-                  S     B        =",
            "    =-     -=-     -=      =-      =========  ==================",
            " =  =       =       =  =  =-      =-       =  =",
            " -  ==     ===     ==  - =-      =-        =  =",
            "==------------------------      =-    -----=  =----------",
            "=-                             =-     =                 =",
            "=                             =-      =                 =",
            "==     P    C  &             ==       = !!   *      B ! =",
            "==============================-       ===================",
            "            =",
            "            -",
        ]
    },
    {
        level: 2,
        backgroundSprite: "level-2-bg",
        backgroundScale: 9,
        levelNote: {
            text: "Juno 31, 3005  \n I finnally finished the shrine a long way east from the err *this* base. \n My comrades and I have been constantly attacked by some hostiles here, \n Like they always ruin, or chipped the portal, which already \n is being weathered by this climate. I removed the stairs from the place \n maybe that should prevent it from degrading \n Note to self: cut the front lawn, the shears are in the chest"
        },
        hasEnemy: true,
        enemySpeed: 200,
        enemyScale: 3,
        item: "shears",
        map: [
            "",
            "",
            "",
            "",
            "                                                                                                                                                                                            F",
            "                                                                                                                                                                                      33333333333       ",
            "                                                                                                                                                                                     3333333333333        ",
            "                                                                                                                                                                                     33         33",
            "                                                                                                                                                                                               @33",
            "                       F                                                                                                                                                                F    33333",
            "             333333 3333333333333                                                                                                                                                    3333333333333   ",
            "               |              |                                                                                                                                                          33333 ",
            "               |              |                                                                                                                                                           |||  ",
            "        F |    |        &   C |                                                                                                                                                           |||  ",
            "     33333333333333 33333333333                                                                                                                                                           |||",
            "      | | | 3333333        33333                                                                                                                                                         F|||",
            "  |   | | | 3333333        333333 3B3                                                                                                                                                 33333333",
            "  |   | | | 3333333 B   P  33333333|3            F          F      F     !         FF         S          B          S           F                           F         F              3333333333",
            "22222222222233333332222222233333333332222222222222222222222222222222222222222222222222222222223|322222222222222222223|3222222222222222222222222222222222222222222222222222222222222222222222222222",
            "                                                                                               |                     |                                                                22222222   ",
            "                                                                                               |                     |                                                                  22",
        ]
    },
    {
        level: 3,
        backgroundSprite: "level-3-bg",
        backgroundScale: 4.6,
        levelNote: {
            text: "Juno 31, 3005  \n I finnally finished the shrine, and it looks a bit weird. \n Well anyway now my comrades and I can safeguard our portals, \n I locked the portal for maintainance reasons, \n the key, its uh hidden somewhere.."
        },
        hasEnemy: false,
        enemySpeed: 200,
        enemyScale: 3,
        item: undefined,
        
        map: [
            "                                                                                   @",
            "                                                                                   |",
            "                                                                              ===========",
            "                                                                               ==--=--==",
            "                                                                                -~~-~~-          ",
            "                                                                                 == ==",                                                                               
            "                                                                               ",
            "                                                                                               -=B=-      -==-      -==-",
            "                                                      )                                         ---",
            "                                             ===========",
            "                                             -         -                                                                   ",
            "                                                                             = !    =",
            "                           =  &    B=                                       ==========                        )         =====B=====",
            "                          ============                                         ~                           ========         ---",
            "                         ====-      -                                          ~",
            "            -           ====-                                            =     ~                       ~",
            "           ==------ ------==            ===(=====               ==========     ~           ====B====   ~                                                                           *",
            "            =             =             -       -               -        -     ~              ---      ~                           ====B====       =       =       =       ==========",
            "            -             -                             *   =                  ~                       ~                              ---          ~       ~       ~        -======-",
            "            -             -                         =========                  ~                       ~         *    B=                           ~       ~       ~         -====-",
            "            = P         B =                         -       -                  ~                       ~    =======(====                           ~       ~       ~          -==-",
            "           ================                                                    ~                       ~    -          -                           ~       ~       ~           --",
            "            - - -     - - -                                                    ~                       ~                                           ~       ~       ~",
            "           -=- -       - -=-                                                   ~                       ~                                           ~       ~       ~",
            "            = -         - =                                                    ~                       ~                                           ~       ~       ~",
            "            =-           -=                                                    ~                       ~                                           ~       ~       ~",
            "=~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~=",
            "-                                                                                                                                                                                              -"
        ]
    },
    {
        level: 4,
        backgroundSprite: "level-4-bg",
        backgroundScale: 5,
        levelNote: {
            text: "Exerpt 3071 AD. \n\n   Due to the planet's unstability it's gravitional pull kept \nreversing at a consistent interval. Studies have been conducted \nin this very laboratory your decades. I as a last remark  will say that \nthe planet's gravitional field will fluctuate more so up to 10s, \n causing the demise of the laboratory \n\nNote: the gravity will be so strong that no one can resist and jump"
        },
        hasEnemy: true,
        enemySpeed: 200,
        enemyScale: 3,
        item: undefined,

        map: [
            "                                                                                                                                                                                     ----------------                                                                                                       ",
            "",
            "",
            "",
            "",
            "                                                                                                                 =---------------                     -----------        -------------              -------------",
            "                                                                                                                 =                                                             *                          ",
            "                                                                    -------------------                          =                                                                                        @",
            "                                                                             *                                   =     S  )                         ~                                                     |",
            "                                                                                                                 ============                       ~                                             ===============",
            "",
            "",
            "                                                                             S                                                       --------=",
            "                                                                                                                                            ==",
            "                                                                                                                                  P          =",
            "               ----------------                ------------------                          -----------------                 ===============(=",
            "                      *",
            "",
            "                                                                             *                                        !! !   =                                      *",
            "=-------------=               =================                  ==========================                ===================                ========          =========           =========",
            "=             =               =",
            "=&                            =",
            "=                             =",
            "===============================                                                                                              ================                                                                                              ",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ]
    },
    {
        level: 5,
        backgroundSprite: "level-5-bg",
        backgroundScale: 7,
        levelNote: {
            text: "Juno 31, 3005  \n I finnally finished the shrine, and it looks a bit weird. \n Well anyway now my comrades and I can safeguard our portals, \n I locked the portal for maintainance reasons, \n the key, its uh hidden somewhere.."
        },
        hasEnemy: true,
        enemySpeed: 200,
        enemyScale: 3,
        

        map: [
            "",
            "",
            "                                                 ",
            "",
            "",
            "",
            "",
            "",
            "    ==== =====",
            "    =        ==",
            "    =        ===",
            "    =   C  B ====",
            "   =====================   ======================",
            "                       =   =                     ",
            "                       =   =                     ",
            "   ---------------------   -----------------------",
            "    =-                                          -=",
            "    =                                S           =",
            "    ==  P       C C C C        ! !      B       ==",
            "   ================================================",
        ]
    }
]